# Generated by Django 3.0.5 on 2020-06-14 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Chave_Acesso')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('active', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], max_length=10, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('image', models.ImageField(upload_to='product_image', verbose_name='Imagem')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('status', models.CharField(choices=[('waiting', 'Em Espera'), ('approved', 'Aprovado'), ('reproved', 'Reprovado')], default='waiting', max_length=50, verbose_name='Status')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Company')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Donor')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.TypeProduct')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='Cupon Usado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('hash', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='hash')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
