# Generated by Django 3.0.5 on 2020-05-08 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAssociate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome')),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Chave_Acesso')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('waiting', 'Em Espera'), ('approved', 'Aprovado'), ('reproved', 'Reprovado')], default='waiting', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='typeproduct',
            name='active',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10, verbose_name='Ativo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typeproduct',
            name='name',
            field=models.CharField(default='-', max_length=255, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False, verbose_name='Cupon Usado')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doador', to='core.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfileInfo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='products.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doador', to='products.Donor'),
            preserve_default=False,
        ),
    ]
